// svelte/src/lib/Cell.svelte
<svelte:options immutable />

<script lang="ts">
	import { clickCell, clickNumberCell, flagCell, gameStore, type GameStatus } from './store/store';
	import mineImage from '$lib/images/mine.svg';
	import crossedMineImage from '$lib/images/crossedMine.svg';
	import flagImage from '$lib/images/flag.svg';
	import { flash, isFlagged, isNumberCell, type GameCell } from './services/cell';
	import MinesNumber from './MinesNumber.svelte';
	import { afterUpdate } from 'svelte';

	export let x: number;
	export let y: number;

	let el: HTMLDivElement;

	const handleClickCell = () => clickCell({ x, y });
	const handleClickNumberCell = () => clickNumberCell({ x, y });
	const handleFlagCell = () => flagCell({ x, y });

	let cellData: GameCell;
	let gameStatus: GameStatus;

	// $: gameStore.subscribe(({ board, status }) => {
	// 	// console.log('🚀 ~ file: Cell.svelte ~ line 28 ~ $:gameStore.subscribe ~ subscribe');
	// 	cellData = board[y][x];
	// 	gameStatus = status;
	// });

	$: {
		cellData = $gameStore.board[y][x];
		gameStatus = $gameStore.status;
	}
	$: console.log(cellData);

	// $: ({ status: gameStatus, board } = $gameStore);
	// $: cellData = board[y][x];

	afterUpdate(() => {
		console.log('Cell');
		// flash(el);
	});
</script>

{#if cellData === 'ExplodedMine'}
	<div bind:this={el} aria-label="Exploded mine" class="cell open exploded" data-open={true}>
		<img class="mine-icon" src={mineImage} alt="mine" />
	</div>
{:else if isNumberCell(cellData)}
	<div
		bind:this={el}
		aria-label={cellData === 0 ? `Open cell` : `Open cell with ${cellData} adjacent cells`}
		on:click={handleClickNumberCell}
		class="cell open"
		data-open={true}
	>
		<MinesNumber value={cellData} />
	</div>
{:else if cellData === 'Mine' && gameStatus === 'lose'}
	<div bind:this={el} aria-label="Revealed mine" class="cell open" data-open={true}>
		<img class="mine-icon" src={mineImage} alt="mine" />
	</div>
{:else if cellData === 'FlaggedEmpty' && gameStatus === 'lose'}
	<div bind:this={el} aria-label="Flagged cell with no mine" class="cell open" data-open={true}>
		<img class="crossed-mine-icon" src={crossedMineImage} alt="crossed mine" />
	</div>
{:else if cellData === 'Mine' && gameStatus === 'win'}
	<div
		bind:this={el}
		aria-label="Flagged cell"
		class="cell closed flagged shadow"
		data-open={false}
	>
		<img class="flag-icon" src={flagImage} alt="flag" />
	</div>
{:else if isFlagged(cellData)}
	<div
		bind:this={el}
		aria-label="Flagged cell"
		class="cell closed flagged shadow"
		data-open={false}
		on:contextmenu|preventDefault={handleFlagCell}
	>
		<img class="flag-icon" src={flagImage} alt="flag" />
	</div>
{:else}
	<div
		bind:this={el}
		aria-label="Unrevealed cell"
		class="cell closed shadow"
		disabled={isFlagged(cellData)}
		data-open={false}
		on:click={handleClickCell}
		on:contextmenu|preventDefault={handleFlagCell}
	/>
{/if}

<style>
	.cell {
		box-sizing: border-box;
		width: 28px;
		height: 28px;
		display: flex;
		justify-content: center;
		align-items: center;
		padding: 0;
		outline: none;
		background: none;
	}

	.open {
		border-color: grey;
		border-style: solid;
		border-width: 0;
		border-top-width: 1px;
		border-left-width: 1px;
	}

	/* .open > * {
		margin: -1px 0 0 -1px;
	} */

	.exploded {
		background-color: red;
	}

	/* .closed {
	}

	.flagged {
	} */

	.flagged:active:not(:disabled) {
		border-color: grey;
		border-style: solid;
		border-width: 0;
		border-top-width: 1px;
		border-left-width: 1px;
	}

	.flag-icon {
		width: 18px;
		height: 18px;
	}

	.mine-icon {
		width: 21px;
		height: 21px;
	}

	.crossed-mine-icon {
		width: 21px;
		height: 21px;
	}
</style>

// src/components/Cell.tsx
import { FC, memo } from 'react';
import { match, when, __ } from 'ts-pattern';
import styled, { css } from 'styled-components';
import { shadow } from '../styles/shadow';
import { Coords } from '../utils/constants';
import { MinesNumber } from './MinesNumber';
import mineImage from '../images/mine.svg';
import crossedMineImage from '../images/crossedMine.svg';
import flagImage from '../images/flag.svg';
import { preventDefault } from '../utils/preventDefault';
import { GameStatus, useGameStore } from '../store/store';
import { useLongPress } from '../utils/useLongPress';
import { isFlagged, isNumberCell } from '../services/cell';

type CellProps = Coords & {
  gameStatus: GameStatus;
};

export const Cell: FC<CellProps> = memo(({ x, y, gameStatus }) => {
  const cellData = useGameStore((state) => state.board[y][x]);
  const clickCell = useGameStore((state) => state.clickCell);
  const clickNumberCell = useGameStore((state) => state.clickNumberCell);
  const flagCell = useGameStore((state) => state.flagCell);

  const handleClickCell = () => clickCell({ x, y });
  const handleClickNumberCell = () => clickNumberCell({ x, y });
  const handleFlagCell = () => flagCell({ x, y });

  const flaggedCellLongPressProps = useLongPress({
    onLongPress: handleFlagCell,
  });
  const closedCellLongPressProps = useLongPress({
    onLongPress: handleFlagCell,
    onClick: handleClickCell,
  });

  return match([cellData, gameStatus] as const)
    .with(['ExplodedMine', __], () => (
      <OpenCell aria-label={`Exploded mine`} exploded>
        <MineIcon />
      </OpenCell>
    ))
    .with([when(isNumberCell), __], ([matchedData]) => (
      <OpenCell
        aria-label={
          matchedData === 0
            ? `Open cell`
            : `Open cell with ${matchedData} adjacent cells`
        }
        onClick={handleClickNumberCell}
      >
        <MinesNumber value={matchedData} />
      </OpenCell>
    ))
    .with(['Mine', 'lose'], () => (
      <OpenCell aria-label={`Revealed mine`}>
        <MineIcon />
      </OpenCell>
    ))
    .with(['FlaggedEmpty', 'lose'], () => (
      <OpenCell aria-label={`Flagged cell with no mine`}>
        <CrossedMineIcon />
      </OpenCell>
    ))
    .with([when(isFlagged), __], () => (
      <ClosedCell
        aria-label={`Flagged cell`}
        onContextMenu={preventDefault(handleFlagCell)}
        isFlagged
        {...flaggedCellLongPressProps}
      >
        <FlagIcon />
      </ClosedCell>
    ))
    .otherwise(() => (
      <ClosedCell
        aria-label={`Unrevealed cell`}
        disabled={isFlagged(cellData)}
        isFlagged={false}
        onContextMenu={preventDefault(handleFlagCell)}
        {...closedCellLongPressProps}
      />
    ));
});

const openCellStyle = css`
  border-color: grey;
  border-style: solid;
  border-width: 0;
  border-top-width: 1px;
  border-left-width: 1px;
`;

export const StyledCell = styled.button.attrs({ 'data-testid': 'cell' })`
  box-sizing: border-box;
  width: 28px;
  height: 28px;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0;
  outline: none;
  background: none;
`;

export const OpenCell = styled(StyledCell).attrs({
  'data-open': true,
})<{ exploded?: boolean }>`
  ${openCellStyle}
  ${({ exploded = false }) =>
    exploded &&
    css`
      background-color: red;
    `}

  & > * {
    margin: -1px 0 0 -1px;
  }
`;

const notFlaggedCellStyle = css`
  &:active:not(:disabled) {
    ${openCellStyle}
  }
`;

export const ClosedCell = styled(StyledCell).attrs({
  'data-open': false,
})<{ isFlagged: boolean }>`
  ${shadow}

  ${(props) => (props.isFlagged ? null : notFlaggedCellStyle)}
`;

const FlagIcon = styled.img.attrs({ src: flagImage, alt: 'flag' })`
  width: 18px;
  height: 18px;
`;

const MineIcon = styled.img.attrs({ src: mineImage, alt: 'mine' })`
  width: 21px;
  height: 21px;
`;

const CrossedMineIcon = styled.img.attrs({
  src: crossedMineImage,
  alt: 'crossed mine',
})`
  width: 21px;
  height: 21px;
`;
