// svelte/src/lib/DifficultySelect.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { gameStore, initGame } from './store/store';
	import { difficultyLevels, type Difficulty } from './utils/constants';

	let difficultyQuery: Difficulty = 'beginner';

	const handleClick = (difficulty: Difficulty) => {
		initGame(difficulty);
		difficultyQuery = difficulty;
	};

	onMount(() => {
		initGame(difficultyQuery);
	});
</script>

<div class="select inverted-shadow">
	{#each difficultyLevels as difficulty (difficulty)}
		<button
			class="shadow"
			class:active={$gameStore.difficulty === difficulty}
			on:click={() => handleClick(difficulty)}
		>
			{difficulty}
		</button>
	{/each}
</div>

<style>
	.select {
		display: flex;
		flex-direction: column;
	}

	button {
		opacity: 0.6;
		margin: 0;
		padding: 0.2rem;
		outline: none;
		cursor: pointer;
		text-transform: capitalize;
		flex-grow: 1;
		color: black;
	}

	.active {
		opacity: 1;
	}
</style>

// src/components/DifficultySelect.tsx
import { FC, useCallback, useEffect } from 'react';
import styled from 'styled-components';
import { invertedShadow, shadow } from '../styles/shadow';
import { Difficulty, difficultyLevels } from '../utils/constants';
import { useQueryString } from '../utils/useQueryString';
import { useGameStore } from '../store/gameStore';

interface ButtonProps {
  active?: boolean;
}

export const DifficultySelect: FC = () => {
  const difficultyState = useGameStore((state) => state.difficulty);
  const initGame = useGameStore((state) => state.initGame);
  const [difficultyQuery, setDifficultyQuery] = useQueryString<Difficulty>(
    'difficulty',
    'beginner',
  );

  const handleClick = useCallback(
    (difficulty: Difficulty) => {
      initGame(difficulty);
      setDifficultyQuery(difficulty);
    },
    [initGame, setDifficultyQuery],
  );

  useEffect(() => {
    handleClick(difficultyQuery);
  }, [difficultyQuery, handleClick]);

  return (
    <Select>
      {difficultyLevels.map((difficulty) => (
        <Button
          key={difficulty}
          active={difficultyState === difficulty}
          onClick={() => handleClick(difficulty)}
        >
          {difficulty}
        </Button>
      ))}
    </Select>
  );
};

const Select = styled.div`
  ${invertedShadow}
  display: flex;
  flex-direction: column;
`;

// TODO: fix text color
const Button = styled.button<ButtonProps>`
  ${shadow}
  opacity: ${({ active }) => (active ? 1 : 0.6)};
  margin: 0;
  padding: 0.2rem;
  outline: none;
  cursor: pointer;
  text-transform: capitalize;
  flex-grow: 1;
`;
