// svelte/src/lib/Game.svelte
<svelte:options immutable />

<script lang="ts">
	import Header from './Header.svelte';
	import Board from './Board.svelte';
	import DifficultySelect from './DifficultySelect.svelte';
</script>

<div class="container shadow">
	<Header />
	<Board />
	<DifficultySelect />
</div>

<style>
	.container {
		box-sizing: border-box;
		padding: 0.4rem;
		user-select: none;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		max-width: calc(100% - 2rem);
		max-height: calc(100% - 2rem);
	}

	@media (max-width: 768px) {
		.container {
			max-width: calc(100% - 1rem);
			max-height: calc(100% - 1rem);
		}
	}
</style>

// src/components/Game.tsx
import { FC } from 'react';
import styled from 'styled-components';
import { shadow } from '../styles/shadow';
import { Board } from './Board';
import { DifficultySelect } from './DifficultySelect';
import { Header } from './Header';

export const Game: FC = () => {
  return (
    <Container>
      <Header />
      <Board />
      <DifficultySelect />
    </Container>
  );
};

const Container = styled.div`
  ${shadow}
  box-sizing: border-box;
  padding: 0.4rem;
  user-select: none;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  max-width: calc(100% - 2rem);
  max-height: calc(100% - 2rem);
  @media (max-width: 768px) {
    max-width: calc(100% - 1rem);
    max-height: calc(100% - 1rem);
  }
`;
