// svelte/src/lib/Header.svelte
<script>
	import MinesCounter from './MinesCounter.svelte';
	import StartGameButton from './StartGameButton.svelte';
	import Timer from './Timer.svelte';
</script>

<header class="inverted-shadow">
	<div class="left">
		<MinesCounter />
	</div>
	<div class="center">
		<StartGameButton />
	</div>
	<div class="right">
		<Timer />
	</div>
</header>

<style>
	header {
		padding: 0.2rem;
		display: flex;
	}

	.left {
		display: flex;
		align-items: center;
		justify-content: flex-start;
		flex: 1;
		overflow: hidden;
	}

	.center {
		display: flex;
		align-items: center;
	}

	.right {
		display: flex;
		align-items: center;
		justify-content: flex-end;
		flex: 1;
		overflow: hidden;
	}
</style>

// src/components/Header.tsx
import { FC } from 'react';
import styled from 'styled-components';
import { invertedShadow } from '../styles/shadow';
import { MinesCounter } from './MinesCounter';
import { StartGameButton } from './StartGameButton';
import { Timer } from './Timer';

export const Header: FC = () => {
  return (
    <Container>
      <Left>
        <MinesCounter />
      </Left>
      <Center>
        <StartGameButton />
      </Center>
      <Right>
        <Timer />
      </Right>
    </Container>
  );
};

const Container = styled.header`
  ${invertedShadow}
  padding: 0.2rem;
  display: flex;
`;

const Left = styled.div`
  display: flex;
  align-items: center;
  justify-content: flex-start;
  flex: 1;
  overflow: hidden;
`;

const Center = styled.div`
  display: flex;
  align-items: center;
`;

const Right = styled.div`
  display: flex;
  align-items: center;
  justify-content: flex-end;
  flex: 1;
  overflow: hidden;
`;
