// svelte/src/lib/MinesCounter.svelte
<script lang="ts">
	import Digits from './Digits.svelte';
	import { gameStore } from './store/store';
	import { boardSizes } from './utils/constants';

	$: flagsCount = $gameStore.flaggedEmptyCount + $gameStore.flaggedMinesCount;
	$: ({ mines } = boardSizes[$gameStore.difficulty]);
	$: minesLeft = mines - flagsCount;
</script>

<Digits value={minesLeft} ariaLabel="mines count" />

// src/components/MinesCounter.tsx
import { FC } from 'react';
import { useGameStore } from '../store/gameStore';
import { boardSizes } from '../utils/constants';
import { Digits } from './Digits';

export const MinesCounter: FC = () => {
  const flagsCount = useGameStore(
    (state) => state.flaggedEmptyCount + state.flaggedMinesCount,
  );
  const difficulty = useGameStore((state) => state.difficulty);
  const { mines } = boardSizes[difficulty];
  const minesLeft = mines - flagsCount;

  return <Digits value={minesLeft} aria-label="mines count" />;
};
