// src/components/Board.tsx
import { FC } from 'react';
import styled from 'styled-components/macro';
import { useGameStore } from '../store/store';
import { invisibleScrollbar } from '../styles/invisibleScrollbar';
import { invertedShadow } from '../styles/shadow';
import { preventDefault } from '../utils/preventDefault';
import { Cell, OpenCell } from './Cell';

const Container = styled.div`
  ${invertedShadow}
  ${invisibleScrollbar}
  box-sizing: border-box;
  width: 100%;
  overflow: scroll;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  margin-top: 0.4rem;
  margin-bottom: 0.4rem;
`;

const Row = styled.div`
  display: flex;

  &:first-child ${OpenCell} {
    border-top-width: 0;
  }

  ${OpenCell}:first-child {
    border-left-width: 0;
  }
`;

const handleContextMenu = preventDefault();

export const Board: FC = () => {
  const board = useGameStore((state) => state.board);

  return (
    <Container
      data-testid="board"
      onContextMenu={handleContextMenu}
      role="none"
    >
      {board.map((row, y) => (
        <Row key={row[0].id} data-testid="row">
          {row.map((cell, x) => (
            <Cell key={cell.id} x={x} y={y} />
          ))}
        </Row>
      ))}
    </Container>
  );
};

// export const Board: FC = () => {
//   const difficulty = useGameStore((state) => state.difficulty);
//   const { width, height } = boardSizes[difficulty];

//   return (
//     <Container
//       data-testid="board"
//       onContextMenu={handleContextMenu}
//       role="none"
//     >
//       {[...range({ to: height })].map((...[, y]) => {
//         return [...range({ to: width })].map((...[, x]) => (
//           <Cell key={`x${x}y${y} ${difficulty}`} x={x} y={y} />
//         ));
//       })}
//     </Container>
//   );
// };

// svelte/src/lib/Board.svelte
<svelte:options immutable />

<script lang="ts">
	import Cell from './Cell.svelte';
	import { gameStore } from './store/store';
	import { boardSizes } from './utils/constants';

	let height: number;
	let width: number;

	gameStore.subscribe(({ difficulty }) => {
		// console.log('store');
		({ height, width } = boardSizes[difficulty]);
	});
</script>

<div class="container inverted-shadow invisible-scrollbar">
	{#each Array.from({ length: height }) as _, y (y)}
		<div class="row">
			{#each Array.from({ length: width }) as _, x (`x: ${x}, y: ${y}`)}
				<Cell {x} {y} />
			{/each}
		</div>
	{/each}
</div>

<style>
	.container {
		box-sizing: border-box;
		width: 100%;
		overflow: scroll;
		display: flex;
		align-items: flex-start;
		flex-direction: column;
		margin-top: 0.4rem;
		margin-bottom: 0.4rem;
	}

	.row {
		display: flex;
	}

	/* TODO: check .open-cell */
	.row:first-child .open-cell {
		border-top-width: 0;
	}

	.open-cell:first-child {
		border-top-width: 0;
	}
</style>
