// react/src/components/Board.tsx
import { FC } from 'react';
import styled from 'styled-components';
import { useGameStore } from '../store/gameStore';
import { invisibleScrollbar } from '../styles/invisibleScrollbar';
import { invertedShadow } from '../styles/shadow';
import { boardSizes } from '../utils/constants';
import { preventDefault } from '../utils/preventDefault';
import { Cell, OpenCell } from './Cell';

const handleContextMenu = preventDefault();

export const Board: FC = () => {
  const difficulty = useGameStore((state) => state.difficulty);
  const { height, width } = boardSizes[difficulty];

  return (
    <Container
      onContextMenu={handleContextMenu}
      role="none"
      data-testid="board"
    >
      {Array.from({ length: height }).map((row, y) => (
        <Row key={y} data-testid="row">
          {Array.from({ length: width }).map((_, x) => (
            <Cell key={`x: ${x}, y: ${y}`} x={x} y={y} />
          ))}
        </Row>
      ))}
    </Container>
  );
};

const Container = styled.div`
  ${invertedShadow}
  ${invisibleScrollbar}
  box-sizing: border-box;
  width: 100%;
  overflow: scroll;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  margin-top: 0.4rem;
  margin-bottom: 0.4rem;
`;

const Row = styled.div`
  display: flex;

  &:first-child ${OpenCell} {
    border-top-width: 0;
  }

  ${OpenCell}:first-child {
    border-left-width: 0;
  }
`;

// svelte/src/lib/Board.svelte
<svelte:options immutable />

<script lang="ts">
	import Cell from './Cell.svelte';
	import { gameStore } from './store/store';
	import { boardSizes } from './utils/constants';

	let height: number;
	let width: number;

	gameStore.subscribe(({ difficulty }) => {
		// console.log('store');
		({ height, width } = boardSizes[difficulty]);
	});
</script>

<div class="container inverted-shadow invisible-scrollbar">
	{#each Array.from({ length: height }) as _, y (y)}
		<div class="row">
			{#each Array.from({ length: width }) as _, x (`x: ${x}, y: ${y}`)}
				<Cell {x} {y} />
			{/each}
		</div>
	{/each}
</div>

<style>
	.container {
		box-sizing: border-box;
		width: 100%;
		overflow: scroll;
		display: flex;
		align-items: flex-start;
		flex-direction: column;
		margin-top: 0.4rem;
		margin-bottom: 0.4rem;
	}

	.row {
		display: flex;
	}

	/* TODO: check .open-cell */
	.row:first-child .open-cell {
		border-top-width: 0;
	}

	.open-cell:first-child {
		border-top-width: 0;
	}
</style>
