// src/components/Timer.tsx
import { EffectCallback, FC, useEffect, useState } from 'react';
import { match } from 'ts-pattern';
import { useGameStore } from '../store/store';
import { Digits } from './Digits';

export const Timer: FC = () => {
  const [value, setValue] = useState(0);
  const gameStatus = useGameStore((state) => state.status);

  useEffect(() => {
    let interval: number | undefined;

    return match(gameStatus)
      .with(
        'playing',
        (): ReturnType<EffectCallback> => {
          interval = window.setInterval(() => {
            setValue((stateValue) => stateValue + 1);
          }, 1000);

          return () => {
            window.clearInterval(interval);
          };
        }
      )
      .with('lose', 'win', () => {
        window.clearInterval(interval);
      })
      .with('starting', () => {
        setValue(0);
      })
      .run();
  }, [gameStatus]);

  return <Digits value={value} />;
};

// svelte/src/lib/Timer.svelte
<script lang="ts">
	import { browser } from '$app/env';
	import { onDestroy } from 'svelte';
	import { get } from 'svelte/store';
	import { match } from 'ts-pattern';
	import Digits from './Digits.svelte';
	import { gameStore, type GameStatus } from './store/store';

	let value = 0;
	let interval: number | undefined;
	let prevStatus: GameStatus = get(gameStore).status;

	// TODO: fix
	gameStore.subscribe(({ status }) => {
		if (!browser) return;

		if (status !== prevStatus) {
			match(status)
				.with('playing', () => {
					interval = window.setInterval(() => {
						value += 1;
					}, 1000);
				})
				.with('lose', 'win', () => {
					window.clearInterval(interval);
				})
				.with('starting', () => {
					value = 0;
				})
				.run();

			prevStatus = status;
		}
	});

	onDestroy(() => {
		if (browser) window.clearInterval(interval);
	});
</script>

<Digits {value} ariaLabel="timer" />
